name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      landing: ${{ steps.filter.outputs.landing }}
      dakota-dreamers: ${{ steps.filter.outputs.dakota-dreamers }}
      tribute-band-the-kills: ${{ steps.filter.outputs.tribute-band-the-kills }}
      mathieu-schmidt: ${{ steps.filter.outputs.mathieu-schmidt }}
      deploy-script: ${{ steps.filter.outputs.deploy-script }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            landing:
              - 'landing/**'
            dakota-dreamers:
              - 'dakota-dreamers/**'
            tribute-band-the-kills:
              - 'tribute-band-the-kills/**'
            mathieu-schmidt:
              - 'mathieu-schmidt/**'
            deploy-script:
              - 'deploy.sh'
              - '.github/workflows/deploy.yml'

  deploy-landing:
    needs: changes
    if: needs.changes.outputs.landing == 'true' || needs.changes.outputs.deploy-script == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy Landing
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        run: ./deploy.sh landing

  deploy-dakota-dreamers:
    needs: changes
    if: needs.changes.outputs.dakota-dreamers == 'true' || needs.changes.outputs.deploy-script == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy Dakota Dreamers
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        run: ./deploy.sh dakota-dreamers

  deploy-tribute-band-the-kills:
    needs: changes
    if: needs.changes.outputs.tribute-band-the-kills == 'true' || needs.changes.outputs.deploy-script == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy Tribute Band The Kills
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        run: ./deploy.sh tribute-band-the-kills

  deploy-mathieu-schmidt:
    needs: changes
    if: needs.changes.outputs.mathieu-schmidt == 'true' || needs.changes.outputs.deploy-script == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy Mathieu Schmidt
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        run: ./deploy.sh mathieu-schmidt
